// Run with: npm test  (tsx --test)
//
// Pins the context-window cost this repo publishes.
//
// Installing an MCP server spends the user's context on every turn, whether or
// not the tools are called. We put that number on the README the way a package
// manager puts install size on a download — which only means anything if it
// cannot quietly go stale.
//
// So this measures the live server and fails HERE, in the repo that can fix it,
// rather than letting the badge make a claim that stopped being true three
// description edits ago.
//
// The assertion is on the PUBLISHED form ("12.9K"), not the raw token count.
// Pinning 12,900 exactly would fail CI on every wording tweak; pinning the
// rounded figure fails exactly when the published claim becomes wrong.
//
// When it fails: run `npm run measure:schema`, confirm the change is intended,
// and update the README badge and the profile table to what it prints.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { initializeMcpServer } from "../src/mcp-handler.js";
// @ts-expect-error -- plain .mjs, no types; measure()/asK()/listTools() are the contract.
import { measure, asK, listTools } from "../scripts/measure-tool-schema.mjs";

const README = readFileSync(new URL("../README.md", import.meta.url), "utf8");
const PREFIX = "mcp__blockrun__";

/** Same projection the CLI harness measures, over an in-process handshake. */
async function measureProfile(profile: string) {
  const server = new McpServer({ name: "test", version: "0.0.0" });
  initializeMcpServer(server, { argv: ["--profile", profile], env: {} });
  const [clientSide, serverSide] = InMemoryTransport.createLinkedPair();
  const client = new Client({ name: "test-client", version: "0.0.0" });
  await Promise.all([server.connect(serverSide), client.connect(clientSide)]);
  const { tools } = await client.listTools();
  await client.close();
  return measure(tools, PREFIX) as {
    tools: number; total: number; descriptions: number; perTool: number;
  };
}

test("the context-cost card states the measured numbers", async () => {
  // The card is generated by `npm run brand:card`, never hand-drawn, so the
  // only way it can lie is if someone edits the SVG or forgets to regenerate.
  // Both variants are checked: a dark-mode reader sees a different file.
  const full = await measureProfile("full");
  const trading = await measureProfile("trading");
  const cut = Math.round((1 - trading.total / full.total) * 100);
  const pct = Math.round((full.total / 200_000) * 100);

  for (const variant of ["context-cost.svg", "context-cost-dark.svg"]) {
    const svg = readFileSync(new URL(`../assets/${variant}`, import.meta.url), "utf8");
    assert.ok(svg.includes(`${asK(full.total)} tokens`), `${variant}: headline figure`);
    assert.ok(svg.includes(`${pct}% of a 200K context window`), `${variant}: reference unit`);
    assert.ok(svg.includes(`${asK(trading.total)} with`), `${variant}: trading figure`);
    assert.ok(svg.includes(`${cut}% less`), `${variant}: saving`);
  }
});

test("the README shows both card variants", () => {
  // Without the <source>, dark-mode readers get the light card on a dark page.
  assert.ok(README.includes('srcset="assets/context-cost-dark.svg"'), "dark source");
  assert.ok(README.includes('src="assets/context-cost.svg"'), "light fallback");
});

test("the profile table states each profile's measured cost", async () => {
  // Every row is a public claim; a trimmed profile that quietly grew would
  // otherwise keep advertising a saving it no longer delivers.
  for (const profile of ["full", "media", "trading", "research", "chat"]) {
    const { total, tools } = await measureProfile(profile);
    // Tolerant of row decoration (`full` carries a *(default)* marker), strict
    // on both numbers — the decoration is prose, the numbers are the claim.
    const row = new RegExp(
      `\\| \`${profile}\`[^|]*\\| ${tools} \\| ${total.toLocaleString()} \\|`,
    );
    assert.match(README, row,
      `README row for ${profile} should read ${tools} tools / ${total.toLocaleString()} tokens`);
  }
});

test("the advertised profile saving is the one measured", async () => {
  const full = await measureProfile("full");
  const trading = await measureProfile("trading");
  const cut = Math.round((1 - trading.total / full.total) * 100);
  assert.ok(README.includes(`${cut}% less context`), `saving should read ${cut}%`);
});

test("descriptions are the majority of the cost, which is why the table ranks them", async () => {
  // Not decoration: it is the finding the whole measurement exists to surface,
  // and if schemas ever overtake descriptions the README's advice is wrong.
  const full = await measureProfile("full");
  assert.ok(
    full.descriptions > full.total / 2,
    `descriptions ${full.descriptions} should exceed half of ${full.total}`,
  );
});

test("a server that dies reports why, instead of waiting out the timeout", async () => {
  // We tell people to point this at other people's servers, where the common
  // failure is a typo'd command. Reporting "timed out" after a silent minute
  // for what was `command not found` in the first 200ms is the difference
  // between a tool someone uses twice and one they use once.
  const started = Date.now();
  await assert.rejects(
    () => listTools(["node", "/nonexistent-mcp-server.js"], { timeoutMs: 30_000 }),
    (err: Error) => {
      assert.match(err.message, /exited with code/, "names the exit");
      assert.match(err.message, /Cannot find module/, "carries the child's stderr");
      return true;
    },
  );
  assert.ok(Date.now() - started < 10_000, "should fail fast, not on the timeout");
});
